In [2]:
numlist = [1,2,3,4,4]
numlist

[1, 2, 3, 4, 4]

In [9]:
import numpy as np

np.mean(numlist)
np.sqrt(4)

np.float64(2.0)

In [15]:
np.linspace(1,10,12)

funout = np.linspace(1, 10, 12)
funout + 2

array([ 3.        ,  3.81818182,  4.63636364,  5.45454545,  6.27272727,
        7.09090909,  7.90909091,  8.72727273,  9.54545455, 10.36363636,
       11.18181818, 12.        ])

In [ ]:
# assignment!
# 1) create a list of 15 numbers from 4 to 100
# 2) round those numbers to the nearest integer, and store in another variable
# 3) print out #2
# 4) print out the square root of each num

In [18]:
# 1
list = np.linspace(4, 100, 15)
list

array([  4.        ,  10.85714286,  17.71428571,  24.57142857,
        31.42857143,  38.28571429,  45.14285714,  52.        ,
        58.85714286,  65.71428571,  72.57142857,  79.42857143,
        86.28571429,  93.14285714, 100.        ])

In [21]:
# 2 # 3
round_list = np.round(list)
round_list

array([  4.,  11.,  18.,  25.,  31.,  38.,  45.,  52.,  59.,  66.,  73.,
        79.,  86.,  93., 100.])

In [22]:
# 4
np.sqrt(round_list)

array([ 2.        ,  3.31662479,  4.24264069,  5.        ,  5.56776436,
        6.164414  ,  6.70820393,  7.21110255,  7.68114575,  8.1240384 ,
        8.54400375,  8.88819442,  9.2736185 ,  9.64365076, 10.        ])