In [1]:
import numpy as np

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.full((5,2),7)

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [11]:
M = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
# assignment!
# 1) create 3 matrices: 2x2, 2x2, 3x2
# 2) compute scalar-matrix multiplication
# 3) add all pairs of matrices

M1 = np.array([[1,2],[3,4]])
M2 = np.eye(2)
M3 = np.full((3,2),5)

print("M1 is\n",M1,"\n\nM2 is\n",M2,"\n\nM3 is\n",M3)

M1 = 2*M1
M2 = 3*M2
M3 = 2*M3

print("\nM1+M2 is\n", M1+M2)
print("\nM3 is\n",M3)
#M1+M3, M2+M3 are impossible

M1 is
 [[1 2]
 [3 4]] 

M2 is
 [[1. 0.]
 [0. 1.]] 

M3 is
 [[5 5]
 [5 5]
 [5 5]]

M1+M2 is
 [[ 5.  4.]
 [ 6. 11.]]

M3 is
 [[10 10]
 [10 10]
 [10 10]]


ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 