In [1]:
import numpy as np

In [4]:
v1 = np.array([2,3,-1],ndmin=2)

print(v1)
print(' ')
print(v1.T)

[[ 2  3 -1]]
 
[[ 2]
 [ 3]
 [-1]]


In [9]:
M = np.round(10*np.random.randn(3,3))

print(M)
print(' ')
print(M.T)

[[ -1.  -4.  -7.]
 [ -0.   4.  10.]
 [  8. -15.  13.]]
 
[[ -1.  -0.   8.]
 [ -4.   4. -15.]
 [ -7.  10.  13.]]


In [10]:
# assignment!
# 1) what happens when we transpose twice? M matrix, MT transpose, MTT
# 2) confirm that the transpose operation works on non-square matrices

MT = M.T
MTT = MT.T
print("MTT is\n", MTT)

m = np.round(10*np.random.randn(2,5))
print("\nNon-square matrix m is\n", m)
print("\nTranspose of m is\n", m.T)

MTT is
 [[ -1.  -4.  -7.]
 [ -0.   4.  10.]
 [  8. -15.  13.]]

Non-square matrix m is
 [[ 8. 10. 13. -0. -1.]
 [ 0.  6. -1. 14. -1.]]

Transpose of m is
 [[ 8.  0.]
 [10.  6.]
 [13. -1.]
 [-0. 14.]
 [-1. -1.]]
