In [1]:
import numpy as np

In [6]:
M1 = np.random.randn(4,5)
M2 = np.random.randn(4,5)

print(np.matmul(M1,M2.T))
print(' ')
print(M1@M2.T)
print(' ')
print(np.matmul(M1,M2.T)-M1@M2.T)

[[-2.86091072 -0.60797067  0.64340583  0.10270066]
 [-2.38944426  1.75703352  0.52486832 -0.39795166]
 [ 3.03336923 -5.27710607 -1.0415677   0.68457495]
 [-1.51889996  4.47930545  1.1767976   1.21620083]]
 
[[-2.86091072 -0.60797067  0.64340583  0.10270066]
 [-2.38944426  1.75703352  0.52486832 -0.39795166]
 [ 3.03336923 -5.27710607 -1.0415677   0.68457495]
 [-1.51889996  4.47930545  1.1767976   1.21620083]]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
# assignment!
# create a 3x3 matrix of integers
# multiply by (1) identity, (2) zeros, (3) that matrix's transpose

M = np.random.randint(0,3,(3,3))
print(M)
print(' ')
print(M@np.eye(3))
print(' ')
print(M@np.zeros((3,3)))
print(' ')
print(M@M.T)

[[1 0 0]
 [0 1 2]
 [2 0 1]]
 
[[1. 0. 0.]
 [0. 1. 2.]
 [2. 0. 1.]]
 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 
[[1 0 2]
 [0 5 2]
 [2 2 5]]
